on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Darwin tests
jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
    - name: Install Protoc
      run: |
        f=$(mktemp)
        curl -sSLo "$f" https://github.com/protocolbuffers/protobuf/releases/download/v28.2/protoc-28.2-osx-aarch_64.zip
        mkdir -p "$HOME/.local"
        unzip -d "$HOME/.local" "$f"
        echo "$HOME/.local/bin" >> "${GITHUB_PATH}"

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Install golang
      run: |
        ./tests/install_go.sh -f -p
        echo "/usr/local/go/bin" >> "${GITHUB_PATH}"

    - name: Install Rust
      run: ./tests/install_rust.sh

    - name: Build utils
      run: ./ci/darwin-test.sh
