on:
  schedule:
    - cron:  '0 23 * * 0'
  workflow_dispatch:

permissions: {}

name: Docs URL Alive Check
jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    # don't run this action on forks
    if: github.repository_owner == 'kata-containers'
    env:
      target_branch: ${{ github.base_ref }}
    steps:
    - name: Set env
      run: |
        echo "GOPATH=${GITHUB_WORKSPACE}" >> "$GITHUB_ENV"
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Install golang
      run: |
        ./tests/install_go.sh -f -p
        echo "/usr/local/go/bin" >> "${GITHUB_PATH}"

    - name: Docs URL Alive Check
      run: |
        make docs-url-alive-check
